ARKOV_OPFOR_infantry = [
	["rhs_msv_emr_rifleman"],
	["rhs_msv_emr_marksman"],
	["rhs_msv_emr_machinegunner"],
	["rhs_vdv_rifleman_asval"],
	["rhs_vdv_marksman_asval"],
	["rhs_msv_sergeant"],
	["rhs_vdv_rifleman_asval"]
];
ARKOV_OPFOR_patrol = [
	["rhs_msv_sergeant", "rhs_msv_medic", "rhs_msv_efreitor", "rhs_msv_arifleman", "rhs_msv_grenadier", "rhs_msv_rifleman"]
];
ARKOV_items_weapons = [
	["rhs_weap_ak103", []],
	["rhs_weap_ak103_1_npz", []],
	["rhs_weap_ak105_npz", []],
	["rhs_weap_ak74m_gp25_npz", []],
	["rhs_weap_ak74m_gp25", []],
	["rhs_weap_rpk74", []],
	["rhs_weap_savz58v_ris", []],
	["rhs_weap_savz58v_rail", []],
	["rhs_weap_pkm", []],
	["rhs_weap_pkp", []],
	["rhs_weap_m4_carryhandle", []],
	["rhs_weap_m4_m203", []],
	["rhs_weap_m4a1_carryhandle", []],
	["rhs_weap_m4a1_m320", []],
	["rhs_weap_m4a1_blockII", []],
	["rhs_weap_m4a1_blockII_KAC", []],
	["rhs_weap_m249_light_L", []],
	["rhs_weap_m249_pip_S_para", []],
	["rhs_weap_m240G", []],
	["rhs_weap_m240b_usmc", []],
	["rhs_weap_m21s_eo", []],
	["rhs_weap_m16a4_m203_acog_usmc", []],
	["rhs_weap_m14_bipod_M8541", []],
	["rhs_weap_m14_socom_rail", []],
	["rhs_weap_m14ebrri_leu", []],
	["rhs_weap_m14_rail_wd", []],
	["rhs_weap_hk416d145_wd", []],
	["rhs_weap_hk416d10_m320", []],
	["rhs_weap_hk416d10_grip3", []],
	["rhs_weap_asval_npz_grip1", []],
	["rhs_weap_aks74n_gp25", []],
	["rhs_weap_aks74n_npz", []],
	["rhs_weap_akms", []],
	["rhs_weap_l1a1_wood", ["rhsgref_acc_l1a1_l2a2"]],
	["rhs_weap_M107_w_leu", []],
	["rhs_weap_M590_8RD", []],
	["rhs_weap_mk18_eotech_sup", []],
	["rhs_weap_mk18_grip2_KAC_wd", []],
	["rhs_weap_mk18_m320", []],
	["rhs_weap_MP44", []],
	["rhs_weap_mk17_STD_grip", []],
	["rhs_weap_mk17_CQC_G33_sup_marsoc", []],
	["rhs_weap_mk17_LB_DMR_marsoc", []],
	["rhs_weap_mg42",[]],
	["rhs_weap_m40_wd_usmc",[]],
	["rhs_weap_m38_rail",[]],
	["rhs_weap_m3a1_specops",[]],
	["rhs_weap_Izh18",[]],
	["rhs_weap_m110",[]],
	["rhs_weap_m24sws_ghillie",[]],
	["rhs_weap_m24sws_wd_leu",[]],
	["rhs_weap_svd_pso1",[]],
	["rhs_weap_svdp_wd_npz",[]],
	["rhs_weap_t5000",[]],
	["rhs_weap_vss_grip_npz",[]],
	["rhs_weap_XM2010_wd_leu", []],
	["rhs_m4_grip_compm4",[]],
	["rhs_weap_m1garand_sa43",[]],
	["rhs_weap_pya",[]],
	["rhs_weap_6p53",[]],
	["rhs_weap_makarov_pm",[]],
	["rhs_weap_makarov_pm",[]],
	["hgun_Pistol_heavy_02_F",[]],
	["rhs_weap_tt33",[]],
	["rhsusf_weap_m1911a1",[]],
	["rhs_weap_fnmag",[]],
	["rhs_weap_aks74un",[]],
	["rhs_weap_m76",[]],
	["rhs_weap_m76",[]]
];

ARKOV_items_attachments = [
	"optic_Hamr",
	"optic_NVS",
	"muzzle_snds_M",
	"muzzle_snds_B",
	"rhs_acc_rakursPM",
	"rhsusf_acc_ACOG",
	"rhsusf_acc_ACOG2_3d",
	"rhsusf_acc_anpeq15",
	"rhsusf_acc_anpeq15_bk",
	"rhsusf_acc_anpeq15_wmx",
	"rhsusf_acc_anpeq15A",
	"rhsusf_acc_anpeq16a",
	"rhsusf_acc_elcan_3d",
	"rhsusf_acc_eotech_552",
	"rhsusf_acc_eotech_552_d",
	"rhsusf_acc_eotech_552_wd",
	"rhsusf_acc_eotech_xps3",
	"rhsusf_acc_g33_T1",
	"rhsusf_acc_g33_xps3",
	"rhsusf_acc_grip2",
	"rhsusf_acc_grip3",
	"rhsusf_acc_harris_bipod",
	"rhsusf_acc_kac_grip",
	"rhsusf_acc_LEUPOLDMK4",
	"rhsusf_acc_LEUPOLDMK4_d",
	"rhsusf_acc_M8541",
	"rhsusf_acc_M8541_mrds",
	"rhsusf_acc_mrds",
	"rhsusf_acc_nt4_black",
	"rhsusf_acc_premier_anpvs27",
	"rhsusf_acc_RM05",
	"rhsusf_acc_rotex5_grey",
	"rhsusf_acc_rotex5_tan",
	"rhsusf_acc_RX01",
	"rhsusf_acc_RX01_NoFilter",
	"rhsusf_acc_SpecterDR",
	"rhsusf_acc_SpecterDR_A",
	"rhsusf_acc_T1_high",
	"rhs_acc_1p29_3d",
	"rhs_acc_1p63",
	"rhs_acc_1p78_3d",
	"rhs_acc_1p87",
	"rhs_acc_1pn34",
	"rhs_acc_1pn93_2",
	"rhs_acc_dh520x56",
	"rhs_acc_ekp1",
	"rhs_acc_ekp1d",
	"rhs_acc_ekp8_02",
	"rhs_acc_ekp8_18",
	"rhs_acc_ekp8_18c",
	"rhs_acc_grip_ffg2",
	"rhs_acc_grip_rk2",
	"rhs_acc_grip_rk6",
	"rhs_acc_mtz",
	"rhs_acc_nita",
	"rhs_acc_okp7_dovetail",
	"rhs_acc_pkas",
	"rhs_acc_pkas",
	"rhs_acc_pso1m2",
	"rhs_acc_pso1m2_ads_night",
	"rhs_acc_pso1m21_pkp",
	"rhs_acc_dtk4short",
	"rhs_acc_tgpa",
	"rhs_acc_dtk4screws",
	"rhs_acc_pbs1",
	"rhs_acc_perst1ik",
	"rhsusf_acc_acc_762sd_silencer"
];

ARKOV_items_vest = [
	"rhs_6b13_Flora_6sh92_radio","rhs_6b13_Flora_6sh92_headset_mapcase","rhs_6b13_Flora_6sh92_vog","rhs_6b13_Flora_crewofficer","rhs_6b13_EMR_6sh92","rhs_6b13_EMR_6sh92_radio","rhs_6b13_EMR_6sh92_headset_mapcase","rhs_6b13_EMR_6sh92_vog","rhs_6b13_EMR","rhs_6b2","rhs_6b2_AK","rhs_6b2_chicom","rhs_6b2_holster","rhs_6b2_lifchik","rhs_6b2_RPK","rhs_6b2_SVD","rhs_6b13_Flora_6sh92","rhs_6b13_Flora","rhs_6b3","rhs_6b3_holster","rhs_6b3_R148","rhs_6b3_off","rhs_6b3_AK","rhs_6b3_AK_2","rhs_6b3_AK_3","rhs_6b3_RPK","rhs_6b3_VOG","rhs_6b3_VOG_2","rhs_6b5_khaki","rhs_6b5_rifleman_khaki","rhs_6b5_officer_khaki","rhs_6b5_medic_khaki","rhs_6b5_sniper_khaki","rhs_6sh117_mg","rhs_6sh117_rifleman","rhs_6sh117_ar","rhs_6sh117_nco","rhs_6sh117_nco_azart","rhs_6sh117_svd","rhs_6sh117_val","rhs_6sh117_grn","rhs_6sh92","rhs_6sh92_headset","rhs_6sh92_radio","rhs_6sh92_vog","rhs_6sh92_vog_headset","rhsgref_alice_webbing","V_PlateCarrier1_blk","V_PlateCarrier1_rgr","V_PlateCarrier1_rgr_noflag_F","V_PlateCarrier1_tna_F","V_PlateCarrier1_wdl","V_PlateCarrier2_blk","V_PlateCarrier2_rgr","V_PlateCarrier2_rgr_noflag_F","V_PlateCarrier2_tna_F","V_PlateCarrier2_wdl","V_Chestrig_blk","V_Chestrig_rgr","V_Chestrig_khk","rhsgref_chestrig","V_Chestrig_oli","rhsgref_chicom","rhs_chicom","V_DeckCrew_violet_F","V_DeckCrew_red_F","V_DeckCrew_green_F","V_DeckCrew_brown_F","V_DeckCrew_blue_F","V_DeckCrew_white_F","V_DeckCrew_yellow_F","V_PlateCarrierIA1_dgtl","V_TacVest_gen_F","rhsusf_iotv_ucp_Rifleman","rhsusf_iotv_ucp_Teamleader","rhsusf_iotv_ucp","V_SmershVest_01_F","V_SmershVest_01_radio_F","V_HarnessOGL_brn","V_HarnessOGL_ghex_F","V_HarnessOGL_gry","V_HarnessO_brn","V_HarnessO_ghex_F","V_HarnessO_gry","V_LegStrapBag_black_F","V_LegStrapBag_coyote_F","V_LegStrapBag_olive_F","rhs_lifchik_NCO","rhs_lifchik_vog","rhs_lifchik","rhs_lifchik_light","rhs_vest_commander","V_CarrierRigKBT_01_EAF_F","V_CarrierRigKBT_01_Olive_F","V_Pocketed_black_F","V_Pocketed_coyote_F","V_Pocketed_olive_F","rhs_gear_OFF","rhssaf_vest_otv_md2camo","rhsgref_otv_digi","rhsgref_otv_khaki","rhssaf_vest_md12_digital","rhssaf_vest_md12_digital_desert","rhssaf_vest_md12_m70_rifleman","rhssaf_vest_md98_digital","rhssaf_vest_md98_md2camo","rhssaf_vest_md98_woodland","rhssaf_vest_md98_rifleman","rhssaf_vest_md99_digital","rhssaf_vest_md99_digital_radio","rhssaf_vest_md99_digital_rifleman","rhssaf_vest_md99_digital_rifleman_radio","rhssaf_vest_md99_md2camo","rhssaf_vest_md99_md2camo_radio","rhssaf_vest_md99_md2camo_rifleman","rhssaf_vest_md99_md2camo_rifleman_radio","rhssaf_vest_md99_woodland","rhssaf_vest_md99_woodland_radio","rhssaf_vest_md99_woodland_rifleman","rhssaf_vest_md99_woodland_rifleman_radio","V_Rangemaster_belt","V_TacVestIR_blk","V_BandollierB_blk","V_BandollierB_cbr","V_BandollierB_ghex_F","V_BandollierB_rgr","V_BandollierB_khk","V_BandollierB_oli","V_TacChestrig_cbr_F","V_TacChestrig_grn_F","V_TacChestrig_oli_F","V_TacVest_blk","V_TacVest_brn","V_TacVest_camo","rhsgref_TacVest_ERDL","V_TacVest_khk","V_TacVest_oli","V_TacVest_blk_POLICE","V_I_G_resistanceLeader_F","V_PlateCarrier_Kerry","rhs_vydra_3m"
];
ARKOV_items_helmet = [
	"rhs_6b26_green","rhs_6b26_bala_green","rhs_6b26_ess_green","rhs_6b26_ess_bala_green","rhs_6b26","rhs_6b26_bala","rhs_6b26_ess","rhs_6b26_ess_bala","rhs_6b27m_green","rhs_6b27m_green_bala","rhs_6b27m_green_ess","rhs_6b27m_green_ess_bala","rhs_6b27m","rhs_6b27m_bala","rhs_6b27m_ess","rhs_6b27m_ess_bala","rhs_6b27m_ml","rhs_6b27m_ml_bala","rhs_6b27m_ml_ess","rhs_6b27m_ML_ess_bala","rhsusf_ach_bare","rhsusf_ach_bare_des","rhsusf_ach_bare_des_ess","rhsusf_ach_bare_des_headset","rhsusf_ach_bare_des_headset_ess","rhsusf_ach_bare_ess","rhsusf_ach_bare_headset","rhsusf_ach_bare_headset_ess","rhsusf_ach_bare_semi","rhsusf_ach_bare_semi_ess","rhsusf_ach_bare_semi_headset","rhsusf_ach_bare_semi_headset_ess","rhsusf_ach_bare_tan","rhsusf_ach_bare_tan_ess","rhsusf_ach_bare_tan_headset","rhsusf_ach_bare_wood","rhsusf_ach_bare_wood_ess","rhsusf_ach_bare_wood_headset","rhsusf_ach_bare_wood_headset_ess","rhsusf_ach_helmet_DCU","rhsusf_ach_helmet_DCU_early","rhsusf_ach_helmet_DCU_early_rhino","rhsusf_ach_helmet_M81","rhsusf_cvc_green_helmet","rhsusf_cvc_green_alt_helmet","rhsusf_cvc_green_ess","rhsusf_cvc_helmet","rhsusf_cvc_alt_helmet","rhsusf_cvc_ess","rhssaf_bandana_digital","rhssaf_bandana_digital_desert","rhssaf_bandana_md2camo","rhssaf_bandana_oakleaf","rhssaf_bandana_smb","H_Bandanna_gry","H_Bandanna_blu","H_Bandanna_cbr","H_Bandanna_khk_hs","H_Bandanna_khk","H_Bandanna_mcamo","H_Bandanna_sgg","H_Bandanna_sand","H_Bandanna_surfer","H_Bandanna_camo","rhsgref_bcap_specter","H_PASGT_basic_black_F","H_PASGT_basic_blue_F","H_PASGT_basic_olive_F","H_PASGT_basic_white_F","rhs_beanie_green","H_Watchcap_blk","H_Watchcap_cbr","rhs_beanie","H_Watchcap_camo","rhssaf_beret_black","rhssaf_beret_green","rhssaf_beret_para","H_Watchcap_khk","rhssaf_beret_red","rhssaf_beret_blue_un","H_Beret_blk","H_Beret_gen_F","rhs_beret_mp2","rhs_beret_mp1","rhs_beret_mvd","rhs_beret_omon","H_Beret_CSAT_01_F","rhsgref_un_beret","rhs_beret_vdv_early","rhs_beret_vdv3","rhs_beret_vdv2","rhs_beret_vdv1","rhs_beret_milp","H_Beret_EAF_01_F","rhs_Booniehat_digi","rhs_Booniehat_flora","rhssaf_booniehat_digital","rhssaf_booniehat_md2camo","rhssaf_booniehat_woodland","H_Booniehat_mgrn","H_Booniehat_khk_hs","H_Booniehat_khk","H_Booniehat_mcamo","H_Booniehat_oli","H_Booniehat_tan","H_Booniehat_taiga","H_Booniehat_tna_F","H_Booniehat_wdl","H_Booniehat_dgtl","H_Booniehat_eaf","rhsgref_Booniehat_alpen","rhs_Booniehat_m81","rhs_booniehat2_marpatd","rhs_booniehat2_marpatwd","rhs_Booniehat_ucp","rhs_Booniehat_ocp","rhsusf_Bowman","rhsusf_bowman_cap","H_Cap_blk","H_Cap_Black_IDAP_F","H_Cap_grn","H_Cap_oli","H_Cap_oli_hs","H_Cap_Orange_IDAP_F","H_Cap_police","H_Cap_press","H_Cap_red","H_Cap_tan","H_Cap_khaki_specops_UK","H_Cap_usblack","H_Cap_tan_specops_US","H_Cap_White_IDAP_F","H_Cap_blk_Raven","H_Cap_brn_SPECOPS","H_HelmetB","H_HelmetB_black","H_HelmetB_camo","H_HelmetB_desert","H_HelmetB_grass","H_HelmetB_sand","H_HelmetB_snakeskin","H_HelmetB_tna_F","H_HelmetB_plain_wdl","rhs_cossack_visor_cap","rhs_cossack_visor_cap_tan","rhs_cossack_papakha","rhs_fieldcap","rhsgref_patrolcap_specter","rhs_fieldcap_digi","rhs_fieldcap_digi2","rhs_fieldcap_izlom","rhs_fieldcap_m88","rhs_fieldcap_m88_back","rhs_fieldcap_m88_grey","rhs_fieldcap_m88_grey_back","rhs_fieldcap_m88_klmk","rhs_fieldcap_m88_klmk_back","rhs_fieldcap_m88_moldovan_ttsko_blue","rhs_fieldcap_m88_moldovan_ttsko_blue_back","rhs_fieldcap_m88_moldovan_ttsko_cold","rhs_fieldcap_m88_moldovan_ttsko_cold_back","rhs_fieldcap_m88_moldovan_ttsko_desat","rhs_fieldcap_m88_moldovan_ttsko_desat_back","rhs_fieldcap_m88_moldovan_ttsko_hot","rhs_fieldcap_m88_moldovan_ttsko_hot_back","rhs_gssh18","H_Construction_basic_orange_F","H_Construction_earprot_orange_F","H_Construction_headset_orange_F","H_Construction_basic_white_F","H_Construction_earprot_white_F","H_Construction_headset_white_F","H_Hat_blue","H_HeadBandage_clean_F","H_HeadBandage_stained_F","H_HeadBandage_bloody_F","rhs_headband","H_HeadSet_black_F","H_CrewHelmetHeli_I","H_CrewHelmetHeli_O","H_CrewHelmetHeli_I_E","H_CrewHelmetHeli_B","H_PilotHelmetHeli_I","H_PilotHelmetHeli_O","H_PilotHelmetHeli_I_E","H_PilotHelmetHeli_B","rhsgref_6b27m_ttsko_digi","rhsgref_6b27m_ttsko_forest","rhsgref_6b27m_ttsko_mountain","rhsgref_6b27m_ttsko_urban","rhsusf_lwh_helmet_M1942","rhsgref_helmet_M1_des","rhsgref_helmet_M1_erdl","rhsgref_helmet_M1_liner","rhsgref_helmet_M1_mit","rhsgref_helmet_M1_bare","rhsgref_helmet_M1_bare_alt01","rhsgref_helmet_M1_painted","rhsgref_helmet_M1_painted_alt01","rhsgref_hat_m1941cap","rhsgref_helmet_m1940","rhsgref_helmet_m1940_camo01","rhsgref_helmet_m1940_alt1","rhsgref_helmet_m1940_camo01_alt1","rhsgref_helmet_m1940_winter_alt1","rhsgref_helmet_m1940_winter","rhsgref_helmet_m1942","rhsgref_helmet_m1942_camo01","rhsgref_helmet_m1942_alt1","rhsgref_helmet_m1942_camo01_alt1","rhsgref_helmet_m1942_winter_alt1","rhsgref_helmet_m1942_winter","rhsgref_helmet_m1942_heergreycover","rhsgref_helmet_m1942_heersplintercover","rhsgref_helmet_m1942_heermarshcover","rhsgref_helmet_m1942_heerwintercover","rhsgref_hat_m43cap_heer","rhsgref_hat_m43cap_heer1_tilted","rhsgref_M56","rhssaf_helmet_m59_85_oakleaf","rhssaf_helmet_m59_85_nocamo","rhssaf_helmet_m97_black_nocamo","rhssaf_helmet_m97_black_nocamo_black_ess","rhssaf_helmet_m97_black_nocamo_black_ess_bare","rhssaf_helmet_m97_md2camo","rhssaf_helmet_m97_md2camo_black_ess","rhssaf_helmet_m97_md2camo_black_ess_bare","rhssaf_helmet_m97_veil_md2camo","rhssaf_helmet_m97_oakleaf","rhssaf_helmet_m97_oakleaf_black_ess","rhssaf_helmet_m97_oakleaf_black_ess_bare","rhssaf_helmet_m97_veil_oakleaf","rhssaf_helmet_m97_olive_nocamo","rhssaf_helmet_m97_olive_nocamo_black_ess","rhssaf_helmet_m97_olive_nocamo_black_ess_bare","rhssaf_helmet_m97_woodland","rhssaf_helmet_m97_woodland_black_ess","rhssaf_helmet_m97_woodland_black_ess_bare","rhssaf_helmet_m97_veil_woodland","H_MilCap_blue","H_MilCap_gen_F","H_MilCap_ghex_F","H_MilCap_grn","H_MilCap_gry","H_MilCap_ocamo","H_MilCap_taiga","H_MilCap_mcamo","H_MilCap_tna_F","H_MilCap_wdl","H_MilCap_dgtl","H_MilCap_eaf","H_HelmetIA","rhs_omon_cap","rhsgref_helmet_pasgt_3color_desert","rhsgref_helmet_pasgt_3color_desert_rhino","rhsgref_helmet_pasgt_altis_lizard","rhsgref_helmet_pasgt_erdl","rhsgref_helmet_pasgt_erdl_rhino","rhsgref_helmet_pasgt_flecktarn","rhsgref_helmet_pasgt_olive","rhsgref_helmet_pasgt_woodland","rhsgref_helmet_pasgt_woodland_rhino","rhsgref_hat_M1951","rhs_pilotka","rhsusf_protech_helmet","rhsusf_protech_helmet_ess","rhsusf_protech_helmet_rhino","H_Shemag_olive","H_Shemag_olive_hs","H_ShemagOpen_khk","H_ShemagOpen_tan","H_Helmet_Skate","rhs_ssh68_2","rhs_ssh60","rhsgref_ssh68_ttsko_forest","rhsgref_ssh68_ttsko_mountain","rhsgref_ssh68_ttsko_dark","rhsgref_ssh68_vsr","H_StrawHat","rhs_tsh4","rhs_tsh4_bala","rhs_tsh4_ess","rhs_tsh4_ess_bala","rhs_ushanka"
];
ARKOV_items_backPack = [
	"rhs_assault_umbts","B_AssaultPack_Kerry","B_AssaultPack_blk","B_AssaultPack_cbr","B_AssaultPack_eaf_F","B_AssaultPack_rgr","B_AssaultPack_ocamo","B_AssaultPack_dgtl","B_AssaultPack_khk","B_AssaultPack_mcamo","B_AssaultPack_sgg","B_AssaultPack_tna_F","B_AssaultPack_wdl_F","B_Carryall_cbr","B_Carryall_eaf_F","B_Carryall_ghex_F","B_Carryall_green_F","B_Carryall_ocamo","B_Carryall_khk","B_Carryall_oli","B_Carryall_mcamo","B_Carryall_taiga_F","B_Carryall_oucamo","B_Carryall_wdl_F","B_CivilianBackpack_01_Everyday_IDAP_F","B_CivilianBackpack_01_Everyday_Vrana_F","B_CivilianBackpack_01_Everyday_Black_F","B_CivilianBackpack_01_Everyday_Astra_F","B_FieldPack_blk","B_FieldPack_cbr","B_FieldPack_ghex_F","B_FieldPack_green_F","B_FieldPack_ocamo","B_FieldPack_khk","B_FieldPack_oli","B_FieldPack_taiga_F","B_FieldPack_oucamo","rhssaf_kitbag_digital","rhssaf_kitbag_md2camo","rhssaf_kitbag_smb","B_Kitbag_cbr","B_Kitbag_rgr","B_Kitbag_mcamo","B_Kitbag_sgg","B_LegStrapBag_black_F","B_LegStrapBag_coyote_F","B_LegStrapBag_olive_F","rhs_medic_bag","B_Messenger_Black_F","B_Messenger_Coyote_F","B_Messenger_Gray_F","B_Messenger_Olive_F","B_Messenger_IDAP_F","rhs_rd54","rhs_rk_sht_30_olive","rhs_rpg_2","rhs_rpg_empty","rhs_rpg_6b2","rhs_rpg_6b3","B_CivilianBackpack_01_Sport_Blue_F","B_CivilianBackpack_01_Sport_Green_F","B_CivilianBackpack_01_Sport_Red_F","rhs_tortila_black","rhsgref_tortila_specter","rhs_tortila_grey","rhs_tortila_emr","rhs_tortila_khaki","rhs_tortila_olive","B_TacticalPack_blk","B_TacticalPack_rgr","B_TacticalPack_ocamo","B_TacticalPack_mcamo","B_TacticalPack_oli"
];
ARKOV_items_misc = [
	"ItemCompass",
	"ItemMap",
	"MineDetector",
	"Binocular",
	"Rangefinder",
	"NVGoggles",
	"NVGoggles_INDEP",
	"Laserdesignator",
	"ACE_CableTie",
	"ACE_Clacker",
	"ACE_DeadManSwitch",
	"ACE_DefusalKit",
	"ACE_EarPlugs",
	"ACE_EntrenchingTool",
	"ACE_Flashlight_KSF1",
	"ACE_Flashlight_XL50",
	"ACE_Kestrel4500",
	"ACE_MX2A",
	"ACE_RangeCard",
	"O_UavTerminal",
	"B_UavTerminal",
	"rhsusf_ANPVS_14",
	"rhsusf_ANPVS_15",
	"rhs_1PN138",
	"rhs_1PN138",
	"rhsusf_bino_lerca_1200_black",
	"rhsusf_bino_leopold_mk4",
	"rhs_pdu4"
];
ARKOV_items_food = [
	"ACE_Banana",
	"ACE_Can_Franta",
	"ACE_Can_RedGull",
	"ACE_Can_Spirit",
	"ACE_Canteen",
	"ACE_Canteen_Empty",
	"ACE_Canteen_Half",
	"ACE_MRE_BeefStew",
	"ACE_MRE_ChickenHerbDumplings",
	"ACE_MRE_ChickenTikkaMasala",
	"ACE_MRE_CreamChickenSoup",
	"ACE_MRE_CreamTomatoSoup",
	"ACE_MRE_LambCurry",
	"ACE_MRE_MeatballsPasta",
	"ACE_MRE_SteakVegetables",
	"ACE_WaterBottle",
	"ACE_WaterBottle_Half",
	"ACE_WaterBottle_Half",
	"ACE_WaterBottle_Half",
	"ACE_WaterBottle_Empty"
];
ARKOV_items_medic = [
	"ACE_bloodIV",
	"ACE_bloodIV_500",
	"ACE_elasticBandage",
	"ACE_epinephrine",
	"ACE_epinephrine",
	"ACE_fieldDressing",
	"ACE_fieldDressing",
	"ACE_fieldDressing",
	"ACE_morphine",
	"ACE_morphine",
	"ACE_packingBandage",
	"ACE_packingBandage",
	"ACE_packingBandage",
	"ACE_personalAidKit",
	"ACE_salineIV",
	"ACE_salineIV_500",
	"ACE_splint",
	"ACE_surgicalKit",
	"ACE_tourniquet"
];